export { FeaturesCard } from "./featuresCard";
export { LoginIntegration } from "./loginIntegration";
export { List } from "./list";
export { HeadingProfile } from "./headingProfile";
export { HeadingMainPage } from "./headingMainPage";
export { Header } from "./header";
export { Footer } from "./footer";
export { LastNotificationList } from "./lastNotificationList";
export { ClinicCard } from "./clinicCard";
